name: Run Linters
on: push

jobs:
  run-linters:
    name: Build and Deploy EcoLuz
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ›ï¸ Check out repo
        uses: actions/checkout@v2

      - name: ğŸ·ï¸ Read node from package.json
        id: node-version-package-json
        uses: culshaw/read-package-node-version-actions@v1

      - name: âš™ï¸ Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.node-version-package-json.outputs.version }}
          cache: 'npm'

      - name: ğŸ’… Run linters
        run: yarn run eslint src --ext .js,.jsx,.ts,.tsx
