name: Run Linters
on: push

jobs:
  run-linters:
    name: Build and Deploy EcoLuz
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ›ï¸ Check out repo
        uses: actions/checkout@v2

      - name: ğŸ·ï¸ Read node from package.json
        id: node-version
        uses: josepdecid/get-nodejs-version-action@v0.0.3-alpha

      - name: âš™ï¸ Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.node-version.outputs.version }}

      # TODO: Install ONLY eslint dependency (extract version from package json)
      - name: ğŸ”§ Install dependencies
        run: yarn install --dev

      - name: ğŸ’… Run linters
        run: yarn run eslint src --ext .js,.jsx,.ts,.tsx
